# Generated by Django 5.2.8 on 2025-11-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=100)),
                ('Province', models.CharField(max_length=100)),
                ('Barangay', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('Zip_code', models.CharField(max_length=100)),
            ],
        ),
    ]
