# Generated by Django 5.2.8 on 2025-11-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mothers_name', models.CharField(max_length=100)),
                ('Mothers_contact', models.CharField(max_length=100)),
                ('Fathers_name', models.CharField(max_length=100)),
                ('Fathers_contact', models.CharField(max_length=100)),
                ('Guardians_name', models.CharField(max_length=100)),
            ],
        ),
    ]
