# Generated by Django 5.2.8 on 2025-11-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_familyinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Elementary_school', models.CharField(max_length=100)),
                ('Highschool', models.CharField(max_length=100)),
                ('Senior_high', models.CharField(max_length=100)),
                ('Tertiary', models.CharField(max_length=100)),
                ('Year_attended', models.IntegerField()),
            ],
        ),
    ]
