# Generated by Django 5.2.8 on 2025-11-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0004_educationalbackground'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(max_length=100)),
                ('Subject_code', models.CharField(max_length=100)),
                ('Schedule', models.CharField(max_length=100)),
                ('Professor', models.CharField(max_length=100)),
                ('Room_number', models.CharField(max_length=100)),
            ],
        ),
    ]
