# Generated by Django 5.2.8 on 2025-11-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0005_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaccount',
            name='LRN',
        ),
        migrations.RemoveField(
            model_name='studentaccount',
            name='Password',
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='Gender',
            field=models.CharField(max_length=20),
        ),
    ]
