# Generated by Django 5.2.8 on 2025-11-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0006_remove_studentaccount_lrn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
    ]
